CREATE TABLE PRODUCTS (
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION NVARCHAR(50),
    STATUS TINYINT NOT NULL DEFAULT 1,        --MEHSULUN AKTIV YOXSA PASSIV OLDUGUNU BILDIRMEK UCUN
    PRICE DECIMAL(10,2) NOT NULL,
    DISCOUNT_PRICE DECIMAL(10,2),
    COST_PRICE DECIMAL(10,2),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_DATE DATETIME DEFAULT GETDATE()
);


CREATE TABLE INVENTORIES (
    ID BIGINT IDENTITY PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    WAREHOUSE_NO INT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_DATE DATETIME DEFAULT GETDATE(),
    CONSTRAINT uq_inventory_product_warehouse
        UNIQUE (PRODUCT_ID, WAREHOUSE_NO),            --HER MEHSUL HER ANBARDA BIR DEFE OLSUN DEYE ETMISEM
    CONSTRAINT fk_inventory_product
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS (ID)             --PRODUCTS TABLE ILE RELATION OLSUN DEYE YARATDIM
        ON DELETE NO ACTION
);

CREATE TABLE ORDERS (
    ID BIGINT IDENTITY PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    DESCRIPTION NVARCHAR(40),
    WAREHOUSE_NO INT NOT NULL,
    STATUS TINYINT NOT NULL DEFAULT 1,               -- 1 = created, 2 = paid, 3 = shipped, 4 = cancelled
                                                    --YARADILMIS SIFARISIN STATUSUNU BILDIRIR: YARANIB, ODENIB, CATDIRILIB, IMTINA EDILIB.

    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_DATE DATETIME DEFAULT GETDATE(),
    CONSTRAINT fk_orders_product
        FOREIGN KEY (PRODUCT_ID)             --PRODUCTS TABLE ILE RELATION OLSUN  VE SIFARISI OLAN MEHSUL SISTEMDEN SILINE BILMESIN DEYE
        REFERENCES PRODUCTS(ID)
        ON DELETE NO ACTION
);

CREATE TRIGGER INVENTORY_UPDATE                --INVENTORIES TABLE DA DEYISIKLIK OLDUGU AN UPDATED_DATE AVTOMATIK DEYISSIN.
ON INVENTORIES 
AFTER UPDATE
AS                    
BEGIN
    UPDATE INVENTORIES                                        
    SET UPDATED_DATE = GETDATE()	
    WHERE ID IN (SELECT ID FROM inserted)
END;

CREATE TRIGGER PRODUCT_UPDATE            --PRODUCTS TABLE DA DEYISIKLIK OLDUGU AN UPDATED_DATE AVTOMATIK DEYISSIN.
ON PRODUCTS
AFTER UPDATE
AS
BEGIN
    UPDATE PRODUCTS                                        
    SET UPDATED_DATE = GETDATE()	
    WHERE ID IN (SELECT ID FROM inserted)
END;

CREATE TRIGGER ORDER_UPDATE          --ORDERS TABLE DA DEYISIKLIK OLDUGU AN UPDATED_DATE AVTOMATIK DEYISSIN.
ON ORDERS
AFTER UPDATE
AS
BEGIN
    UPDATE ORDERS                                        
    SET UPDATED_DATE = GETDATE()	
    WHERE ID IN (SELECT ID FROM inserted)
END;




