
CREATE PROCEDURE usp_ProcessOrder
    @PRODUCT_ID BIGINT,
    @WAREHOUSE_NO INT,
    @QUANTITY INT,
    @PRICE DECIMAL(10,2)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRAN;

        DECLARE @STOCK INT;

        SELECT @STOCK = QUANTITY
        FROM INVENTORIES WITH (UPDLOCK, ROWLOCK)
        WHERE PRODUCT_ID = @PRODUCT_ID
          AND WAREHOUSE_NO = @WAREHOUSE_NO;

        IF @STOCK >= @QUANTITY
        BEGIN
            UPDATE INVENTORIES
            SET QUANTITY = QUANTITY - @QUANTITY
            WHERE PRODUCT_ID = @PRODUCT_ID
              AND WAREHOUSE_NO = @WAREHOUSE_NO;

            INSERT INTO ORDERS (PRODUCT_ID, QUANTITY, PRICE, WAREHOUSE_NO)
            VALUES (@PRODUCT_ID, @QUANTITY, @PRICE, @WAREHOUSE_NO);

            COMMIT;
            SELECT 'SUCCESS' AS Result;
        END
        ELSE
        BEGIN
            ROLLBACK;
            SELECT 'OUT_OF_STOCK' AS Result;
        END
END;
