ALTER DATABASE PRACTISE
SET ALLOW_SNAPSHOT_ISOLATION ON;



SET TRANSACTION ISOLATION LEVEL SNAPSHOT;


    SELECT
        P.CODE, 
        P.NAME,
        SUM(O.QUANTITY) AS TOTAL_SOLD,
        I.QUANTITY 
    FROM PRODUCTS P WITH (NOLOCK)
    LEFT JOIN ORDERS O WITH (NOLOCK) ON P.ID=O.PRODUCT_ID
    LEFT JOIN INVENTORIES I WITH (NOLOCK) ON P.ID=I.PRODUCT_ID
    GROUP BY P.CODE, P.NAME, I.QUANTITY
    ORDER BY SUM(O.QUANTITY) DESC

--SATILMIS MEHSULUN CODE, NAME, TOPLAM NE QEDER SATILDIGI VE ANLIQ ANBAR MIQDARINI GOSTEREN VE EN COX SATILANDAN EN AZ SATILMIS
--MEHSUL UZRE DUZULMUS KOD